name: CI Tests

on:
  push:
    branches: [ "main", "master", "develop", "ci-test-failure", "ci-test-success" ]
  pull_request:
    branches: [ "main", "master", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Run Test Suite
      # Ejecuta la batería de pruebas en modo estándar (sin --full)
      run: |
        bash ./instalar.sh --test
