name: CI Tests

on:
  push:
    branches: [ "main", "master", "develop", "ci-test-failure", "ci-test-success" ]
  pull_request:
    branches: [ "main", "master", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Run Test Suite
      id: run-tests
      continue-on-error: true
      run: |
        bash -x ./instalar.sh --test > ci_log.txt 2>&1
        
    - name: Upload log
      uses: actions/upload-artifact@v4
      with:
        name: ci-log
        path: ci_log.txt
        
    - name: Fail if tests failed
      if: steps.run-tests.outcome == 'failure'
      run: exit 1
